
services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: my-project-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - my-project

    db:
        image: postgres:15
        container_name: my-project-db
        environment:
            POSGRES_DB: ${DB_HOST}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:${DB_PORT}"
        volumes:
            - my-project-db-data:/var/lib/postgresql/data
        networks:
            - my-project

    nginx:
        image: nginx:alpine
        container_name: my-project-nginx
        ports:
            - "${APP_PORT}:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - my-project

volumes:
    my-project-db-data:

networks:
    my-project:
